sudo: required

language: python

python:
  - "3.6"

stages:
  - name: test
  - name: deploy
    if: tag IS present

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - export REPO=cassinyio/cassiny-spawner

services:
  - docker

jobs:
  include:
    - stage: test
      install:
        - sudo apt-get update
        - sudo apt-get install docker-ce
      script:
        - make test
        - make clean-docker
    - stage: deploy
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - export TAG=$TRAVIS_BRANCH
        - docker build -f Dockerfile -t $REPO:$TAG .
        - docker tag $REPO:$TAG $REPO:latest
        - docker push $REPO

notifications:
  webhooks:
    urls:
      - https://webhooks.cassiny.io
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
