sudo: required

language: python
python:
  - "3.6"

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

stages:
  - test
  - name: deploy
    if: branch = master

before_install:
  - sudo apt-get update
  - sudo apt-get install docker-ce

script:
  - pip install tox
  - make test
  - make clean-docker

jobs:
  include:
    - stage: deploy
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - export REPO=cassinyio/cassiny-spawner
        - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
        - docker build -f Dockerfile -t $REPO:$COMMIT .
        - docker tag $REPO:$COMMIT $REPO:$TAG
        - docker push $REPO

notifications:
  webhooks:
    urls:
      - https://webhooks.cassiny.io
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false