sudo: required

language: python

python:
  - "3.6"

stages:
  - name: test
  - name: deploy
    if: tag IS present

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=cassinyio/cassiny-spawner
    - DB_USER=postgres
    - DB_PASSWORD=mysecretpassword
    - DB_PORT=15432
    - STREAM_URI=nats://localhost:4222

services:
  - docker

jobs:
  include:
    - stage: test
      install:
        - sudo apt-get update
        - sudo apt-get install docker-ce
        - docker run -d --name streams -p 4222:4222 nats-streaming:0.6.0
        - docker run -d --name postgres -e POSTGRES_DB=$POSTGRES_DB -e POSTGRES_USER=$POSTGRES_USER -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -p $DB_PORT:5432 postgres:10.0
        - docker swarm init
      script:
        - make lint
        - make test
      after_success:
        - docker rm -f streams
        - docker rm -f postgres
        - docker swarm leave -f
        - codecov
    - stage: deploy
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - export TAG=$TRAVIS_BRANCH
        - docker build -f Dockerfile -t $REPO:$TAG .
        - docker tag $REPO:$TAG $REPO:latest
        - docker push $REPO

notifications:
  webhooks:
    urls:
      - https://webhooks.cassiny.io
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
