# Copyright (c) 2017, Cassiny.io OÜ

FROM python:3.6.4-alpine

LABEL maintainer "wow@cassiny.io"

RUN apk update && \
    apk add build-base \
    postgresql-dev \
    libffi-dev

RUN mkdir /src
WORKDIR /src
COPY . /src
COPY keys/ /keys

# Install python packages
RUN pip install -r requirements/ci.txt
RUN pip install -r requirements/common.txt
