# Copyright (c) 2017, Cassiny.io OÜ

FROM python:3.6.4

LABEL maintainer "wow@cassiny.io"

USER root

RUN mkdir /src
WORKDIR /src
COPY . /src
COPY keys/ /keys

# Install python packages
RUN pip install -r requirements/ci.txt
RUN pip install -r requirements/common.txt
